version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependency
  versioning-strategy: increase
  ignore:
  - dependency-name: nikic/php-parser
    versions:
    - ">= 0"
  - dependency-name: phpstan/phpstan
    versions:
    - ">= 0"
  - dependency-name: zendframework/zend-servicemanager
    versions:
    - ">= 0"
  commit-message:
    prefix: Build
    include: scope
